services:
  routeros:
    image: evilfreelancer/docker-routeros:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
      - /dev/kvm
    ports:
      - "21:21"
      - "4433:443"
      - "1194:1194"
      - "1701:1701"
      - "500:500"
      - "1723:1723"
      - "2027:2027"
      - "8291:8291"
      - "8900:8900"
      - "22:22"
      - "23:23"
      - "8089:80"
      - "5900:5900"
      - "8728:8728"
      - "8729:8729"